const images = import.meta.glob<{ default: string }>('../assets/images/*.jpg', { eager: true, query: '?url' });

/**
 * Given a filename or a legacy path (e.g. './images/foo.jpg'),
 * resolves it to the bundled asset URL generated by Vite.
 */
export const getImageUrl = (pathOrUrl: string): string => {
  if (!pathOrUrl) return "";
  
  // If it's a data URL, blob, or external HTTP URL, just return it
  if (pathOrUrl.startsWith('data:') || pathOrUrl.startsWith('blob:') || pathOrUrl.startsWith('http')) {
    return pathOrUrl;
  }
  
  // Extract just the filename from the path
  const filename = pathOrUrl.split('/').pop() || "";
  
  // Find it in our imported glob
  const match = Object.keys(images).find(p => p.endsWith(`/${filename}`));
  if (match) {
    return images[match].default;
  }
  
  // If we can't find it in our bundle, fallback to whatever was passed (e.g. it might be a user's custom url)
  return pathOrUrl;
};
